import type { Config } from 'tailwindcss';
// this type error should be fixed by the tailwindcss-animate team soon
import twAnimate from 'tailwindcss-animate';
import containerQueries from '@tailwindcss/container-queries';
import { fontFamily } from 'tailwindcss/defaultTheme';
// for Editor's non controlling HTML elements like <h1>, <p>, <ul>, <li>, etc.
import twTypography from '@tailwindcss/typography';

export const colorPalette = {
  wool: {
    DEFAULT: 'hsl(var(--wool))',
    dark: 'hsl(var(--wool-dark))',
    light: 'hsl(var(--wool-light))',
  },
  ash: {
    DEFAULT: 'hsl(var(--ash))',
    medium: 'hsl(var(--ash-medium))',
    light: 'hsl(var(--ash-light))',
    lighter: 'hsl(var(--ash-lighter))',
    lightest: 'hsl(var(--ash-lightest))',
  },
  gold: 'hsl(var(--gold))',
  beryl: 'hsl(var(--beryl))',
  mosaic: 'hsl(var(--mosaic))',
  heart: 'hsl(var(--heart))',
  ribbon: 'hsl(var(--ribbon))',
  junglegreen: 'hsl(var(--junglegreen))',
  danger: 'hsl(var(--danger))',
  text: {
    pri: 'hsl(var(--text-pri))',
    sec: 'hsl(var(--text-sec))',
    opt: 'hsl(var(--text-opt))',
    brand: 'hsl(var(--text-brand))',
    cta: 'hsl(var(--text-cta))',
    cta2: 'hsl(var(--text-cta2))',
    destructive: 'hsl(var(--text-destructive))',
    invert: 'hsl(var(--text-invert))',
  },
  surface: {
    pri: 'hsl(var(--surface-pri))',
    sec: 'hsl(var(--surface-sec))',
    opt: 'hsl(var(--surface-opt))',
    brand: 'hsl(var(--surface-brand))',
    cta: 'hsl(var(--surface-cta))',
    'cta-bg': 'hsl(var(--surface-cta-bg))',
    destructive: 'hsl(var(--surface-destructive))',
    invert: 'hsl(var(--surface-invert))',
  },
  icon: {
    pri: 'hsl(var(--icon-pri))',
    sec: 'hsl(var(--icon-sec))',
    brand: 'hsl(var(--icon-brand))',
    cta: 'hsl(var(--icon-cta))',
    destructive: 'hsl(var(--icon-destructive))',
    invert: 'hsl(var(--icon-invert))',
  },
  border: {
    pri: 'hsl(var(--border-pri))',
    sec: 'hsl(var(--border-sec))',
    opt: 'hsl(var(--border-opt))',
    brand: 'hsl(var(--border-brand))',
    cta: 'hsl(var(--border-cta))',
    destructive: 'hsl(var(--border-destructive))',
    invert: 'hsl(var(--border-invert))',
  },
} as const;

export const themeColors = {
  border: 'hsl(var(--border))',
  input: 'hsl(var(--input))',
  ring: 'hsl(var(--ring))',
  background: 'hsl(var(--background))',
  foreground: 'hsl(var(--foreground))',
  primary: {
    DEFAULT: 'hsl(var(--primary))',
    foreground: 'hsl(var(--primary-foreground))',
  },
  secondary: {
    DEFAULT: 'hsl(var(--secondary))',
    foreground: 'hsl(var(--secondary-foreground))',
  },
  destructive: {
    DEFAULT: 'hsl(var(--destructive))',
    foreground: 'hsl(var(--destructive-foreground))',
  },
  success: {
    DEFAULT: 'hsl(var(--success))',
    foreground: 'hsl(var(--success-foreground))',
  },
  muted: {
    DEFAULT: 'hsl(var(--muted))',
    foreground: 'hsl(var(--muted-foreground))',
  },
  accent: {
    DEFAULT: 'hsl(var(--accent))',
    foreground: 'hsl(var(--accent-foreground))',
  },
  popover: {
    DEFAULT: 'hsl(var(--popover))',
    foreground: 'hsl(var(--popover-foreground))',
  },
  card: {
    DEFAULT: 'hsl(var(--card))',
    foreground: 'hsl(var(--card-foreground))',
  },
};

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  prefix: '~',
  theme: {
    container: {
      center: true,
      padding: '2em',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        ...colorPalette,
        ...themeColors,
      },
      borderRadius: {
        sm: '2px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '4xl': '32px',
        '5xl': '40px',
        '6xl': '52px',
      },
      fontFamily: {
        sans: ['var(--font-sans)', ...fontFamily.sans],
        serif: ['var(--font-serif)', ...fontFamily.serif],
        mono: ['var(--font-mono)', ...fontFamily.mono],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'scale-up': {
          from: { transform: 'scaleY(0)', transformOrigin: 'bottom' },
          to: { transform: 'scaleY(1)', transformOrigin: 'bottom' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'scale-up': 'scale-up 0.5s ease-out',
      },
      // because consuming apps that use the stupid "font-size: 62.5%" html hack throw off rem units
      spacing: {
        '0': '0px',
        '1': '0.25em',
        '2': '0.5em',
        '3': '0.75em',
        '4': '1em',
        '5': '1.25em',
        '6': '1.5em',
        '7': '1.75em',
        '8': '2em',
        '9': '2.25em',
        '10': '2.5em',
        '11': '2.75em',
        '12': '3em',
        '14': '3.5em',
        '16': '4em',
        '20': '5em',
        '24': '6em',
        '28': '7em',
        '32': '8em',
        '36': '9em',
        '40': '10em',
        '44': '11em',
        '48': '12em',
        '52': '13em',
        '56': '14em',
        '60': '15em',
        '64': '16em',
        '72': '18em',
        '80': '20em',
        '96': '24em',
        px: '1px',
        '0.5': '0.125em',
        '1.5': '0.375em',
        '2.5': '0.625em',
        '3.5': '0.875em',
      },
      lineHeight: {
        none: '1',
        tight: '1.25',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
        '13': '52px',
        '14': '60px',
        '15': '68px',
        '16': '72px',
        '17': '96px',
        '18': '120px',
        '19': '128px',
        '20': '136px',
        '21': '144px',
      },
      fontSize: {
        '2xs': ['8px', { lineHeight: '12px' }],
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
        '4xl': ['32px', { lineHeight: '40px' }],
        '5xl': ['36px', { lineHeight: '44px' }],
        '6xl': ['40px', { lineHeight: '52px' }],
        '7xl': ['44px', { lineHeight: '56px' }],
        '8xl': ['48px', { lineHeight: '60px' }],
        '9xl': ['52px', { lineHeight: '68px' }],
        '10xl': ['60px', { lineHeight: '76px' }],
        '11xl': ['68px', { lineHeight: '88px' }],
        '12xl': ['72px', { lineHeight: '96px' }],
        '13xl': ['96px', { lineHeight: '120px' }],
        '14xl': ['128px', { lineHeight: '144px' }],
      },
    },
  },
  plugins: [twAnimate, containerQueries, twTypography],
} satisfies Config;
